### ISSUE TITLE
Segfault when building

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [radxa/u-boot#150]
Branch: `next-dev-v2024.10`
Commit: 45aa10f3ced32f45bb336fb38925f14ac924c98e

Building segfaults, reverting #148 and 45aa10f3ced32f45bb336fb38925f14ac924c98e fixes it. Built via armbian build framework, full log is here: https://paste.armbian.com/jomegemugo

Snippet with the error message:

```
aarch64-linux-gnu-ld.bfd: warning: u-boot has a LOAD segment with RWX permissions
   aarch64-linux-gnu-ld.bfd: arch/arm/mach-rockchip/built-in.o: in function `misc_require_recovery':
   /armbian/cache/sources/u-boot-worktree/u-boot-rockchip64/next-dev-v2024.10/arch/arm/mach-rockchip/boot_mode.c:29:(.text.misc_require_recovery+0x1c): undefined reference to `android_get_bootdev'
   aarch64-linux-gnu-ld.bfd: arch/arm/mach-rockchip/built-in.o: in function `resource_scan':
   /armbian/cache/sources/u-boot-worktree/u-boot-rockchip64/next-dev-v2024.10/arch/arm/mach-rockchip/resource_img.c:365:(.text.resource_scan+0x8): undefined reference to `android_get_bootdev'
   aarch64-linux-gnu-ld.bfd: arch/arm/mach-rockchip/built-in.o: in function `rockchip_read_resource_file':
   /armbian/cache/sources/u-boot-worktree/u-boot-rockchip64/next-dev-v2024.10/arch/arm/mach-rockchip/resource_img.c:434:(.text.rockchip_read_resource_file+0x24): undefined reference to `android_get_bootdev'
   aarch64-linux-gnu-ld.bfd: lib/built-in.o: in function `get_size_of_partition':
   /armbian/cache/sources/u-boot-worktree/u-boot-rockchip64/next-dev-v2024.10/lib/avb/libavb_user/avb_ops_user.c:79:(.text.get_size_of_partition+0x14): undefined reference to `android_get_bootdev'
   aarch64-linux-gnu-ld.bfd: lib/built-in.o: in function `get_unique_guid_for_partition':
   /armbian/cache/sources/u-boot-worktree/u-boot-rockchip64/next-dev-v2024.10/lib/avb/libavb_user/avb_ops_user.c:353:(.text.get_unique_guid_for_partition+0x1c): undefined reference to `android_get_bootdev'
   aarch64-linux-gnu-ld.bfd: lib/built-in.o:/armbian/cache/sources/u-boot-worktree/u-boot-rockchip64/next-dev-v2024.10/lib/avb/libavb_user/avb_ops_user.c:166: more undefined references to `android_get_bootdev' follow
   Segmentation fault (core dumped)
   make: *** [Makefile:1291: u-boot] Error 139
```

**Comment by JohnTheCoolingFan** [comment]
Due to a3173ae8a83cb05c78bccfa7cd73ed4b591e67ef doesn't happen anymore, at least without `CONFIG_ANDROID_BOOTLOADER`
